var dict = {
    "tuân thủ": "conform   /kənˈfɔːm/",
    "hợp đồng": "agreement   /əˈɡriː.mənt/",
    "đảm bảo": "secure   /sɪˈkjʊər/",
    "hủy bỏ": "cancellation   /ˌkæn.səlˈeɪ.ʃən/",
    "mục đích": "determine   /dɪˈtɝː.mɪn/",
    "thuê": "engage   /ɪnˈɡeɪdʒ/",
    "thành lập": "establish   /ɪˈstæb.lɪʃ/",
    "bắt buộc": "mandatory   /ˈmæn.də.tɔːr.i/",
    "buổi tiệc": "party   /ˈpɑː.ti/",
    "điều khoản": "provision   /prəˈvɪʒ.ən/",
    "giải quyết": "solve   /sɒlv/ ",
    "riêng": "specific   /spəˈsɪf.ɪk/",
    "truy cập": "access   /ˈæk.ses/",
    "chỉ định": "designate   /ˈdez.ɪɡ.neɪt/",
    "tương thích": "compatible   /kəmˈpæt.ə.bəl/",
    "xóa bỏ": "delete   /dɪˈliːt/",
    "trưng bày": "display   /dɪˈspleɪ/",
    "bản sao": "duplicate   /ˈdʒuː.plɪ.keɪt/",
    "sự thất bại": "failure   /ˈfeɪ.ljər/",
    "tìm ra": "figure out   /ˈfɪɡər/",
    "Làm lơ": "ignore   /ɪɡˈnɔːr/",
    "Tìm kiếm": "search   /sɝːtʃ/",
    "tắt": "shut down   /ʃʌt/",
    "cảnh báo": "warning   /ˈwɔː.nɪŋ/",
    "phong phú": "abundant   /əˈbʌn.dənt/",
    "thành tựu": "accomplishment   /əˈkɑːm.plɪʃ.mənt/",
    "gom lại": "bring together   /brɪŋ/",
    "ứng cử viên": "candidate   /ˈkæn.dɪ.deɪt/",
    "nghĩ ra": "come up with   /kʌm/",
    "tương xứng": "commensurate   /kəˈmen.sjər.ət/",
    "trận đấu": "match   /mætʃ/",
    "Hồ sơ": "profile   /ˈproʊ.faɪl/",
    "trình độ chuyên môn": "qualifications   /ˌkwɒl.ɪ.fɪˈkeɪ.ʃən/",
    "tuyển dụng": "recruit   /rɪˈkruːt/ ",
    "Gửi đi": "submit   /səbˈmɪt/",
    "mất thời gian": "time-consuming   /ˈtaɪm.kənˌsjuː.mɪŋ/",
    "trả giá": "bargain   /ˈbɑː.ɡɪn/",
    "chịu": "bear   /beər/",
    "hành vi": "behavior   /bɪˈheɪ·vjər/",
    "Thủ tục thanh toán": "checkout   /ˈtʃek.aʊt/",
    "thoải mái": "comfort   /ˈkʌm.fət/",
    "mở rộng": "extend   /ɪkˈstend/",
    "khám phá": "explore   /ɪkˈsplɔːr/",
    "mục": "item   /ˈaɪ.təm/",
    "hàng hóa": "merchandise   /ˈmɜː.tʃən.daɪs/",
    "nghiêm chỉnh": "strictly   /ˈstrɪkt.li/",
    "khuynh hướng": "trend   /trend/",
    "Chấp nhận": "accept   /əkˈsept/",
    "thăng bằng": "balance   /ˈbæl.əns/",
    "vay": "borrow   /ˈbɒr.əʊ/",
    "thận trọng": "conservative   /kənˈsɜː.və.tɪv/",
    "khấu trừ": "deduct   /dɪˈdʌkt/",
    "cổ tức": "dividend   /ˈdɪv.ɪ.dend/",
    "tiền đặt cọc": "down payment   /ˌdaʊn ˈpeɪ.mənt/",
    "thế chấp": "mortgage   /ˈmɔː.ɡɪdʒ/",
    "hạn chế": "restricted   /rɪˈstrɪk.tɪd/",
    "Chữ ký": "signature   /ˈsɪɡ.nə.tʃər/",
    "đưa ra": "take out   /teɪk aʊt/",
    "Giao dịch": "transaction   /trænˈzæk.ʃən/",
    "liền kề": "adjacent   /ˈæk.sənt/",
    "hợp tác": "collaboration   /kəˌlæb.əˈreɪ.ʃən/",
    "tập trung": "concentrate   /ˈkɒn.sən.treɪt/",
    "thuận lợi": "conducive   /kənˈdʒuː.sɪv/",
    "gián đoạn": "disruption   /dɪsˈrʌpʃən/",
    "cản trở": "hamper   /ˈhæm.pər/",
    "không cẩn thận": "inconsiderately   /ˌɪn.kənˈsɪd.ər.ət/ ",
    "sảnh đợi": "lobby   /ˈlɒb.i/",
    "đi lên": "move up   /muːv ʌp/ ",
    "mở": "open to   /ˈəʊ.pən tʊ/ ",
    "opt": "opt   /ɒpt/ ",
    "xem xét kỹ lưỡng": "scrutiny   /ˈskruː.tɪ.ni/",
    "kháng cáo": "appeal   /əˈpiːl/",
    "đến": "arrive   /əˈraɪv/ ",
    "thỏa hiệp": "compromise   /ˈkɒm.prə.maɪz/ ",
    "táo bạo": "daringly   /ˈdeə.rɪŋ/",
    "Quen biết": "familiar   /fəˈmɪl.i.ər/",
    "hướng dẫn": "guide   /ɡaɪd/",
    "số đông": "majority   /məˈdʒɒr.ə.ti/",
    "pha trộn": "mix   /mɪks/ ",
    "dựa": "rely   /rɪˈlɑɪ/",
    "chủ quan": "subjective   /səbˈdʒek.tɪv/",
    "gợi ý": "suggestion   /səˈdʒes.tʃən/",
    "đặc vụ": "agent   /ˈeɪ.dʒənt/ ",
    "sự thông báo": "announcement   /əˈnaʊns.mənt/",
    "đồ uống": "beverage   /ˈbev.ər.ɪdʒ/",
    "cái mền": "blanket   /ˈblæŋ.kɪt/ ",
    "bảng": "board   /bɔːd/",
    "yêu cầu": "require   /rɪˈkwaɪər/",
    "sự chậm trễ": "delay   /dɪˈleɪ/",
    "khởi hành": "depart   /dɪˈpɑːt/",
    "bắt tay": "embarkation   /ˌem.bɑːˈkeɪ.ʃən/",
    "hành trình": "itinerary   /aɪˈtɪn.ər.ər.i/ ",
    "cấm": "prohibit   /prəˈhɪb.ɪt/ ",
    "có hiệu lực": "effective   /ɪˈfek.tɪv/ ",
    "đạt được": "obtain   /əbˈteɪn/",
    "phối hợp": "combine   /kəmˈbaɪn/",
    "tiếp tục": "continue   /kənˈtɪn.juː/",
    "sự miêu tả": "description   /dɪˈskrɪp.ʃən/",
    "phân tán": "disperse   /dɪˈspɜːs/",
    "sự giải trí": "entertainment   /en.təˈteɪn.mənt/ ",
    "ảnh hưởng": "influence   /ˈɪn.flu.əns/",
    "phạm vi": "range   /reɪndʒ/ ",
    "giải phóng": "release   /rɪˈliːs/ ",
    "đại diện": "representation   /ˌrep.rɪ.zenˈteɪ.ʃən/",
    "riêng biệt": "separately   /ˈsep.ər.ət.li/",
    "kế tiếp": "successive   /səkˈses.ɪv/",
    "hàng năm": "annually   /ˈæn.ju.ə.li/",
    "cuộc hẹn": "appointment   /əˈpɔɪnt.mənt/ ",
    "đánh giá": "evaluate   /ɪˈvæl.ju.eɪt/",
    "chẩn đoán": "diagnose   /ˈdaɪ.əɡ.nəʊz/",
    "dụng cụ": "instrument   /ˈɪn.strə.mənt/ ",
    "quản lý": "manage   /ˈmæn.ɪdʒ/",
    "ngăn chặn": "preclude   /prɪˈkluːd/",
    "sự giới thiệu": "recommendation   /ˌrek.ə.menˈdeɪ.ʃən/ ",
    "ghi lại": "record   /rɪˈkɔːd/",
    "tham khảo": "refer   /rɪˈfɜːr/",
    "nghiêm trọng": "serious   /ˈsɪə.ri.əs/",
    "chứa": "accommodate   /əˈkɒm.ə.deɪt/ ",
    "sắp xếp": "arrangement   /əˈreɪndʒ.mənt/",
    "hiệp hội": "association   /əˌsəʊ.siˈeɪ.ʃən/",
    "tham gia": "take part in   /teɪk pɑːt ɪn/",
    "liên lạc": "get in touch   /ɡet ɪn tʌtʃ/",
    "giữ": "hold   /həʊld/",
    "vị trí": "location   /ləʊˈkeɪ.ʃən/",
    "quá đông": "overcrowded   /ˌəʊ.vəˈkraʊ.dɪd/",
    "Đăng ký": "register   /ˈredʒ.ɪ.stər/",
    "lựa chọn": "select   /sɪˈlekt/",
    "phiên": "session   /ˈseʃ.ən/",
    "tập hợp": "assemble   /əˈsem.bəl/",
    "Tới trước": "beforehand   /bɪˈfɔː.hænd/",
    "sự phức tạp": "complication   /ˌkɒm.plɪˈkeɪ.ʃən/",
    "chuyển phát nhanh": "courier   /ˈkʊr.i.ər/",
    "bày tỏ": "express   /ɪkˈspres/",
    "gập lại": "fold   /fəʊld/",
    "bố trí": "layout   /ˈleɪ.aʊt/",
    "đề cập đến": "mention   /ˈmen.ʃən/",
    "kiến nghị": "petition   /pəˈtɪʃ.ən/",
    "bằng chứng": "proof   /pruːf/",
    "xem lại": "revise   /rɪˈvaɪz/",
    "thành tích": "achievement   /əˈtʃiːv.mənt/",
    "Góp phần": "contribute   /kənˈtrɪb.juːt/",
    "cống hiến": "dedication   /ˌded.ɪˈkeɪ.ʃən/",
    "trông mong": "look forward to   /lʊk/",
    "nhìn vào": "look to   /lʊk/",
    "trung thành": "loyal   /ˈlɔɪ.əl/",
    "thu hút": "attract   /əˈtrækt/",
    "đối chiếu": "compare   /kəmˈpeər/ ",
    "cuộc thi": "competition   /ˌkɒm.pəˈtɪʃ.ən/ ",
    "tiêu thụ": "consume   /kənˈsjuːm/ ",
    "thuyết phục": "persuasion   /pəˈsweɪ.ʒən/",
    "hiện tại": "present   /ˈprez.ənt/",
    "ham mê": "fad   /fæd/",
    "cảm hứng": "inspiration   /ˌɪn.spˈreɪ.ʃən/",
    "thị trường": "market   /ˈmɑː.kɪt/",
    "năng suất": "yield   /jiːld/",
    "sự thỏa mãn": "satisfaction   /ˌsæt.ɪsˈfæk.ʃən/ ",
    "giá cả phải chăng": "affordable   /əˈfɔː.də.bəl/",
    "khi cần": "as needed   /ˈniː.dɪd/",
    "chịu trách nhiệm": "be in charge of   /tʃɑːdʒ/",
    "sức chứa": "capacity   /kəˈpæs.ə.ti/",
    "bền chặt": "durable   /ˈdʒʊə.rə.bəl/ ",
    "sáng kiến": "initiative   /ɪˈnɪʃ.ə.tɪv/ ",
    "thể chất": "physically   /ˈfɪz.ɪ.kəl.i/ ",
    "các nhà cung cấp": "provider   /prəˈvaɪ.dər/",
    "tái phát": "recur   /rɪˈkɜːr/",
    "giảm": "reduction   /rɪˈdʌk.ʃən/",
    "ở trên đỉnh của": "stay on top of   /steɪ/",
    "cổ phần": "stock   /stɒk/",
    "có khả năng": "ability   /əˈbɪl.ə.ti/",
    "ứng dụng": "apply   /əˈplaɪ/",
    "lý lịch": "background   /ˈbæk.ɡraʊnd/",
    "sẵn sàng cho": "be ready for   /biː ˈred.i fɔːr/",
    "gọi trong": "call in   /ˈkɔːl.ɪn/ ",
    "sự tự tin": "confidence   /ˈkɒn.fɪ.dəns/",
    "liên tục": "constantly   /ˈkɒn.stənt.li/ ",
    "chuyên gia": "expert   /ˈek.spɜːt/",
    "theo sát": "follow up   /ˈfɒl.əʊ.ʌp/",
    "do dự": "hesitant   /ˈhez.ɪ.tənt/",
    "yếu đuối": "weakly   /ˈwiːk.li/",
    "đa dạng hóa": "diversify   /daɪˈvɜː.sɪ.faɪ/",
    "doanh nghiệp": "enterprise   /ˈen.tə.praɪz/",
    "bản chất": "essentially   /ɪˈsen.ʃəl.i/",
    "Hằng ngày": "everyday   /ˈev.ri.deɪ/",
    "chức năng": "function   /ˈfʌŋk.ʃən/",
    "duy trì": "maintain   /meɪnˈteɪn/",
    "điều kiện tiên quyết": "prerequisite   /ˌpriːˈrek.wɪ.zɪt/",
    "chất lượng": "quality   /ˈkwɒl.ə.ti/",
    "trơn tru": "smooth   /smuːð/",
    "nguồn": "resource   /rɪˈzɔːs/",
    "văn phòng phẩm": "stationery   /ˈsteɪ.ʃən.ər.i/",
    "kế toán": "accounting   /əˈkaʊn.tɪŋ/",
    "tích trữ": "accumulate   /əˈkjuː.mjə.leɪt/",
    "tài sản": "asset   /ˈæs.et/",
    "kiểm toán": "audit   /ˈɔː.dɪt/",
    "ngân sách": "budget   /ˈbʌdʒ.ɪt/",
    "xây dựng": "built up   /ˌbɪltˈʌp/",
    "khách hàng": "customer   /ˈkʌs.tə.mər/ ",
    "món nợ": "debt   /det/",
    "nổi bật": "outstanding   /ˌaʊtˈstæn.dɪŋ/",
    "có lãi": "profitably   /ˈprɒfɪtəbli/",
    "hòa giải": "reconcile   /ˈrek.ən.saɪl/",
    "doanh số": "turnover   /ˈtɜːnˌəʊ.vər/",
    "chương trình nghị sự": "agenda   /əˈdʒen.də/",
    "Mang lên": "bring up   /brɪŋ ʌp/",
    "kết luận": "conclude   /kənˈkluːd/",
    "đi trước": "go ahead   /ɡəʊ əˈhed/",
    "mục tiêu": "goal   /ɡəʊl/",
    "dài dòng": "lengthy   /ˈleŋ.θi/",
    "vấn đề": "matter   /ˈmæt.ər/",
    "định kỳ": "periodically   /ˌpɪə.riˈɒd.ɪ.kəl.i/",
    "sự ưu tiên": "priority   /praɪˈɒr.ə.ti/",
    "phát triển": "progress   /ˈprəʊ.ɡres/",
    "chất thải": "waste   /weɪst/",
    "căn bản": "basic   /ˈbeɪ.sɪk/",
    "hoàn thành": "fulfill   /fʊlˈfɪl/",
    "hưng phấn": "excite   /ɪkˈsaɪt/ ",
    "hương vị": "flavor   /ˈfleɪ.vər/",
    "quên": "forget   /fəˈɡet/",
    "thành phần": "element   /ˈel.ɪ.mənt/",
    "thẩm phán": "judge   /dʒʌdʒ/",
    "trộn lên": "mix-up   /ˈmɪks.ʌp/",
    "người bảo trợ": "patron   /ˈpeɪ.trən/",
    "dự đoán": "predict   /prɪˈdɪkt/",
    "ngẫu nhiên": "randomly   /ˈræn.dəm.li/",
    "nhắc lại": "remind   /rɪˈmaɪnd/ ",
    "đôi pho vơi": "deal with   /diːl/",
    "Nơi Đến": "destination   /ˌdes.tɪˈneɪ.ʃən/",
    "phân biệt": "distinguish   /dɪˈstɪŋ.ɡwɪʃ/",
    "tiết kiệm": "economize   /iˈkɒn.ə.maɪz/",
    "tương đương": "equivalent   /ɪˈkwɪv.əl.ənt/",
    "chuyến tham quan": "excursion   /ɪkˈskɜː.ʃən/",
    "chi phí": "expense   /ɪkˈspens/",
    "tương lai": "prospective   /prəˈspek.tɪv/",
    "tình hình": "situation   /ˌsɪtʃ.uˈeɪ.ʃən/",
    "đáng kể": "substantially   /səbˈstæn.ʃəl.i/",
    "hệ thống": "system   /ˈsɪs.təm/",
    "hoạt động": "action   /ˈæk.ʃən/ ",
    "tiếp cận": "approach   /əˈprəʊtʃ/",
    "khán giả": "audience   /ˈɔː.di.əns/",
    "sáng tạo": "creative   /kriˈeɪ.tɪv/",
    "hội thoại": "dialogue   /ˈdaɪ.ə.lɒɡ/",
    "kinh nghiệm": "experience   /ɪkˈspɪə.ri.əns/",
    "xảy ra": "occur   /əˈkɜːr/",
    "biểu diễn": "perform   /pəˈfɔːm/",
    "diễn tập": "rehearse   /rəˈhɜːs/",
    "ôn tập": "review   /rɪˈvjuː/",
    "bán hết": "sell out   /sel/",
    "nhận thức": "perceptive   /pəˈsep.tɪv/",
    "bắt kịp": "catch up   /kætʃ/",
    "mất tập trung": "distraction   /dɪˈstræk.ʃən/",
    "sự khuyến khích": "encouragement   /ɪnˈkʌr.ɪdʒ.mənt/ ",
    "hiển nhiên": "evident   /ˈev.ɪ.dənt/",
    "thói quen": "habit   /ˈhæb.ɪt/",
    "chiếu sáng": "illuminate   /ɪˈluː.mɪ.neɪt/ ",
    "kích thích": "irritate   /ˈɪr.ɪ.teɪt/",
    "Tổng quat": "overview   /ˈəʊ.və.vjuː/",
    "Chức vụ": "position   /pəˈzɪʃ.ən/",
    "thường xuyên": "frequently   /ˈfriː.kwənt.li/",
    "khôi phục": "restore   /rɪˈstɔːr/",
    "n: Xứng đáng": "merit   /ˈmer.ɪt/",
    "chắc chắn": "obviously   /ˈɒb.vi.əs.li/",
    "khuyến khích": "promote   /prəˈməʊt/",
    "sự công nhận": "recognition   /ˌrek.əɡˈnɪʃ.ən/",
    "giá trị": "value   /ˈvæl.juː/",
    "điều chỉnh": "adjustment   /əˈdʒʌst.mənt/",
    "tự động": "automatically   /ˌɔː.təˈmæt.ɪ.kəl.i/",
    "quan trọng": "crucial   /ˈkruː.ʃəl/",
    "sự khác biệt": "discrepancy   /dɪˈskrep.ən.si/",
    "làm phiền": "disturb   /dɪˈstɜːb/",
    "trách nhiệm pháp lý": "liability   /ˌlaɪ.əˈbɪl.ə.ti/",
    "phản ánh": "reflection   /rɪˈflek.ʃən/",
    "chạy": "run   /rʌn/",
    "quét": "scan   /skæn/",
    "trừ": "subtract   /səbˈtrækt/",
    "tẻ nhạt": "tedious   /ˈtiː.di.əs/",
    "kiểm chứng": "verify   /ˈver.ɪ.faɪ/",
    "khao khát": "desire   /dɪˈzaɪər/",
    "chi tiết": "detail   /ˈdiː.teɪl/",
    "dự báo": "forecast   /ˈfɔː.kɑːst/",
    "cấp độ": "level   /ˈlev.əl/",
    "tổng thể": "overall   /ˌəʊ.vəˈrɔːl/",
    "Góc nhìn cá nhân": "perspective   /pəˈspek.tɪv/",
    "dự án": "project   /ˈprɒdʒ.ekt/",
    "thực tế": "realistic   /ˌrɪəˈlɪs.tɪk/ ",
    "Mục tiêu": "target   /ˈtɑː.ɡɪt/",
    "dịch": "translation   /trænzˈleɪ.ʃən/",
    "thông thường": "usually   /ˈjuː.ʒu.ə.li/ ",
    "đặc trưng": "characteristic   /ˌkær.ək.tˈrɪs.tɪk/",
    "kết quả": "result   /rɪˈzʌlt/ ",
    "xem xét": "examine   /ɪɡˈzæm.ɪn/",
    "che": "cover   /ˈkʌv.ər/",
    "hết hạn": "expiration   /ˌek·spəˈreɪ·ʃən/",
    "bao hàm, ngụ ý": "imply   /ɪmˈplaɪ/",
    "lời hứa": "promise   /ˈprɒm.ɪs/",
    "bảo vệ": "protect   /prəˈtekt/",
    "uy tín": "reputation   /ˌrep.jəˈteɪ.ʃən/",
    "đa dạng": "variety   /vəˈraɪ.ə.ti/",
    "sự đánh giá": "appreciation   /əˌpriː.ʃiˈeɪ.ʃən/",
    "được làm bằng": "be made of   /meɪd/",
    "mang vào": "bring in   /brɪŋ/",
    "tình cờ": "casually   /ˈkæʒjuəli/",
    "mã": "code   /koʊd/",
    "lộ ra": "expose   /ɪkˈspəʊz/",
    "nhìn thoáng qua": "glimpse   /ɡlɪmps/ ",
    "ra khỏi": "get out of   /ˌɡet.aʊt.əvˌ/",
    "lỗi thời": "outdated   /ˌaʊtˈdeɪ.tɪd/",
    "thực hành": "practice   /ˈpræk.tɪs/",
    "củng cố": "reinforce   /ˌriː.ɪnˈfɔːs/",
    "bằng lời nói": "verbally   /ˈvɜː.bəl.i/",
    "hạnh kiểm": "conduct   /kənˈdʌkt/",
    "tạo ra": "generate   /ˈdʒen.ə.reɪt/",
    "Thuê": "hire   /haɪər/",
    "theo kịp với": "keep up with   /kip/",
    "tìm đến": "look up to   /lʊk/",
    "người hướng dẫn": "mentor   /ˈmen.tɔːr/",
    "theo dõi": "on track   /træk/",
    "Từ chối": "reject   /rɪˈdʒekt/",
    "thiết lập": "set up   /ˈset.ʌp/",
    "sự thành công": "success   /səkˈses/",
    "đào tạo": "training   /ˈtreɪ.nɪŋ/",
    "cập nhật": "update   /ʌpˈdeɪt/",
    "chính xác": "exact   /ɪɡˈzækt/",
    "vận chuyển": "carrier   /ˈkær.i.ər/",
    "mục lục": "catalog   /ˈkæt̬·əlˌɔɡ, -ˌɑɡ/",
    "không thể thiếu": "integral   /ˈɪn.tɪ.ɡrəl/",
    "hàng tồn kho": "inventory   /ˈɪn.vən.tər.i/",
    "giảm thiểu": "minimize   /ˈmɪn.ɪ.maɪz/",
    "trên tay": "on hand   /hænd/",
    "nhớ lại": "remember   /rɪˈmem.bər/ ",
    "tàu": "ship   /ʃɪp/",
    "đủ": "sufficiently   /səˈfɪʃ.ənt.li/",
    "cung cấp": "supply   /səˈplaɪ/",
    "tích cực": "aggressively   /əˈɡres.ɪv/",
    "Thái độ": "attitude   /ˈæt.ɪ.tʃuːd/",
    "cam kết": "commit   /kəˈmɪt/",
    "quỹ": "fund   /fʌnd/",
    "đầu tư": "invest   /ɪnˈvest/",
    "lâu dài": "long-term   /ˌlɒŋˈtɜːm/",
    "danh mục đầu tư": "portfolio   /ˌpɔːtˈfəʊ.li.əʊ/",
    "kéo ra": "pull out   /pʊl/",
    "trở về": "return   /rɪˈtɜːn/",
    "khôn ngoan": "wisely   /ˈwaɪz.li/",
    "nhãn hiệu": "brand   /brænd/",
    "khiếm khuyết": "defect   /ˈdiː.fekt/",
    "nâng cao": "advanced   /ədˈvɑːnst/",
    "quần áo": "garment   /ˈɡɑː.mənt/",
    "quan sát": "inspect   /ɪnˈspekt/",
    "đẩy lùi": "repel   /rɪˈpel/",
    "lấy lại": "take back   /teɪk/",
    "ném ra": "throw out   /θrəʊ/",
    "thống nhất": "uniformly   /ˈjuː.nɪ.fɔːm.li/",
    "nếp nhăn": "wrinkle   /ˈrɪŋ.kəl/",
    "gánh nặng": "burden   /ˈbɜː.dən/",
    "chuyển": "delivery   /dɪˈlɪv.ər.i/",
    "sang trọng": "deluxe   /dɪˈlʌks/",
    "rơi xuống": "fall to   /fɔːl/",
    "gây ấn tượng": "impress   /ɪmˈpres/",
    "cá nhân": "individual   /ˌɪn.dɪˈvɪdʒ.u.əl/",
    "danh sách": "list   /lɪst/",
    "nhiều": "multiple   /ˈmʌl.tɪ.pəl/",
    "hẹp": "narrow   /ˈnær.əʊ/",
    "nhặt lên": "pick up   /pɪk/",
    "toàn diện": "comprehensive   /ˌkɒm.prɪˈhen.sɪv/",
    "danh mục": "directory   /dɪˈrek.tər.i/",
    "thời lượng": "duration   /djʊəˈreɪ.ʃən/",
    "phụ đề": "entitle   /ɪnˈtaɪ.təl/",
    "giá vé": "fare   /feər/",
    "bù lại": "offset   /ˌɒfˈset/",
    "vận hành": "operate   /ˈɒp.ər.eɪt/",
    "đúng giờ": "punctually   /ˈpʌŋk.tʃu.ə.li/",
    "tương đối": "relatively   /ˈrel.ə.tɪv.li/",
    "phần còn lại": "remainder   /rɪˈmeɪn.dər/",
    "Xa xôi": "remote   /rɪˈməʊt/",
    "có sẵn": "available   /əˈveɪ.lə.bəl/",
    "nới rộng": "broaden   /ˈbrɔː.dən/",
    "thể loại": "category   /ˈkæt.ə.ɡri/",
    "khác biệt": "disparate   /ˈdɪs.pər.ət/",
    "chia": "divide   /dɪˈvaɪd/",
    "ủng hộ": "favor   /ˈfeɪ.vər/",
    "bản năng": "instinct   /ˈɪn.stɪŋkt/",
    "thích hơn": "prefer   /prɪˈfɜːr/",
    "lý do": "reason   /ˈriː.zən/",
    "thư giãn": "relaxation   /ˌriː.lækˈseɪ.ʃən/",
    "nếm thử": "taste   /teɪst/",
    "thúc giục": "urge   /ɜːdʒ/",
    "cho phép": "allow   /əˈlaʊ/",
    "thay thế": "replace   /rɪˈpleɪs/",
    "khía cạnh": "aspect   /ˈæs.pekt/",
    "liên quan": "concern   /kənˈsɜːn/",
    "nhấn mạnh": "emphasize   /ˈem.fə.saɪz/",
    "gánh chịu": "incur   /ɪnˈkɜːr/",
    "nhân viên": "personnel   /ˌpɜː.sənˈel/",
    "chính sách": "policy   /ˈpɒl.ə.si/",
    "phần": "portion   /ˈpɔː.ʃən/",
    "bất kể": "regardless   /rɪˈɡɑːd.ləs/",
    "lương": "salary   /ˈsæl.ər.i/",
    "bộ đồ": "suit   /sjuːt/",
    "E sợ": "apprehensive   /ˌæp.rɪˈhen.sɪv/",
    "hoàn cảnh": "circumstance   /ˈsɜː.kəm.stɑːns/",
    "điều kiện": "terms   /tɜrmz",
    "do": "due to   /dʒuː/",
    "dao động": "fluctuate   /ˈflʌk.tʃu.eɪt/ ",
    "chỉ số": "indicator   /ˈɪn.dɪ.keɪ.tər/ ",
    "cho thuê": "lease   /liːs/",
    "khóa vào": "lock into   /lɒk ˈɪn.tuː/ ",
    "chiếm": "occupy   /ˈɒk.jə.paɪ/",
    "Lựa chọn": "option   /ˈɒp.ʃən/ ",
    "tùy thuộc vào": "subject to   /ˈsʌb.dʒekt/ ",
    "hỗ trợ": "assist   assist",
    "danh từ: Tọa độ": "coordinate   /kəʊˈɔː.dɪ.neɪt/",
    "kích thước": "dimension   /ˌdɪˈmen.ʃən/",
    "chung": "joint   /dʒɔɪnt/",
    "lý tưởng": "ideally   /aɪˈdɪə.li/ ",
    "thời gian dẫn": "lead time   /ˈliːd ˌtaɪm/ ",
    "kế hoạch": "plan   /plæn/",
    "gần": "proximity   /prɒkˈsɪm.ə.ti/ ",
    "điều tiết": "regulate   /ˈreɡ.jə.leɪt/ ",
    "Địa điểm": "site   /saɪt/",
    "sân khấu": "stage   /steɪdʒ/",
    "bận": "busy   /ˈbɪz.i/",
    "trùng hợp": "coincide   /ˌkəʊ.ɪnˈsaɪd/",
    "sự hoang mang": "confusion   /kənˈfjuː.ʒən/",
    "tiếp xúc": "contact   /ˈkɒn.tækt/ ",
    "thất vọng": "disappoint   /ˌdɪs.əˈpɔɪnt/ ",
    "có ý định": "intend   /ɪnˈtend/ ",
    "Địa chỉ": "address   /əˈdres/ ",
    "tránh": "avoid   /əˈvɔɪd/",
    "chứng minh": "demonstrate   /ˈdem.ən.streɪt/",
    "phát triển, xây dựng": "develop   /dɪˈvel.əp/ ",
    "tụ họp": "gather   /ˈɡæð.ər/",
    "phục vụ": "offer   /ˈɒf.ər/ ",
    "chủ yếu": "primarily   /praɪˈmer.əl.i/",
    "rủi ro": "risk   /rɪsk/",
    "chiến lược": "strategy   /ˈstræt.ə.dʒi/",
    "mạnh": "strong   /strɒŋ/",
    "đĩa": "disk   /dɪsk/ ",
    "tạo điều kiện": "facilitate   /fəˈsɪl.ɪ.teɪt/ ",
    "mạng": "network   /ˈnet.wɜːk/",
    "phổ biến": "disseminate   /dɪˈsem.ɪ.neɪt/",
    "quá trình": "process   /ˈprəʊ.ses/ ",
    "Cuộc cách mạng": "revolution   /ˌrev.əˈluː.ʃən/ ",
    "nhọn": "sharp   /ʃɑːp/ ",
    "kỹ năng": "skill   /skɪl/ ",
    "phần mềm": "software   /ˈsɒft.weər/",
    "cửa hàng": "store   /stɔːr/",
    "về mặt kỹ thuật": "technically   /ˈtek.nɪ.kəl.i/",
    "nền tảng": "basis   /ˈbeɪ.sɪs/ ",
    "coi chừng": "be aware of   /biː əˈweər əv/",
    "lợi ích": "benefit   /ˈben.ɪ.fɪt/",
    "đền bù": "compensate   /ˈkɒm.pən.seɪt/",
    "tinh tế": "delicately   /ˈdel.ɪ.kət/",
    "đủ điều kiện": "eligible   /ˈel.ɪ.dʒə.bəl/ ",
    "linh hoạt": "flexibly   /ˈflek.sə.bli/",
    "đàm phán": "negotiate   /nəˈɡəʊ.ʃi.eɪt/",
    "về hưu": "retire   /rɪˈtaɪər/",
    "từ bỏ": "relinquish   /rɪˈlɪŋ.kwɪʃ/",
    "tiền lương": "wage   /weɪdʒ/",
    "sạc điện": "charge   /tʃɑːdʒ/",
    "biên dịch": "compile   /kəmˈpaɪl/ ",
    "giảm giá": "discount   /ˈdɪs.kaʊnt/ ",
    "Có hiệu quả": "efficient   /ɪˈfɪʃ.ənt/",
    "ước tính": "estimate   /ˈes.tɪ.meɪt/",
    "áp đặt": "impose   /ɪmˈpəʊz/ ",
    "sai lầm": "mistake   /mɪˈsteɪk/",
    "đặt hàng": "order   /ˈɔː.dər/ ",
    "kịp thời": "promptly   /ˈprɒmpt.li/ ",
    "cải chính": "rectify   /ˈrek.tɪ.faɪ/",
    "phép tính": "calculation   /ˌkæl.kjəˈleɪ.ʃən/",
    "hạn chót": "deadline   /ˈded.laɪn/ ",
    "tập tin": "file   /faɪl/ ",
    "điền": "fill out   /fɪl aʊt/",
    "bỏ cuộc": "give up   /ɡɪv ʌp/",
    "173": "173   /əʊ/ ",
    "phạt": "penalty   /ˈpen.əl.ti/ ",
    "sự chuẩn bị": "preparation   /ˌprep.ərˈeɪ.ʃən/",
    "Hoàn tiền": "refund   /ˌriːˈfʌnd/",
    "vợ / chồng": "spouse   /spaʊs/",
    "giữ lại": "withhold   /wɪðˈhəʊld/",
    "lo lắng": "nervously   /ˈnɜː.vəs.li/ ",
    "xác minh": "ascertain   /ˌæs.əˈteɪn/",
    "giả định": "assume   /əˈsjuːm/",
    "thập kỷ": "decade   /ˈdek.eɪd/",
    "thí nghiệm": "experiment   /ɪkˈsper.ɪ.mənt/ ",
    "hợp lý": "logical   /ˈlɒdʒ.ɪ.kəl/ ",
    "nghiên cứu": "research   /rɪˈsɜːtʃ/",
    "nhiệm vụ": "responsibility   /rɪˌspɒn.sɪˈbɪl.ə.ti/ ",
    "giám sát viên": "supervisor   /ˈsuː.pə.vaɪ.zər/ ",
    "có hệ thống": "systematically   /ˌsɪs.təˈmæt.ɪ.kəl.i/ ",
    "quen với": "accustom to   /əˈkʌs.təm tuː/",
    "học nghề": "apprentice   /əˈpren.tɪs/",
    "ẩm thực": "culinary   /ˈkʌl.ɪ.nər.i/ ",
    "nhu cầu": "demand   /dɪˈmɑːnd/",
    "vẽ tranh": "draw   /drɔː/",
    "kết hợp": "incorporate   /ɪnˈkɔː.pər.eɪt/",
    "dòng": "influx   /ˈɪn.flʌks/ ",
    "phương pháp": "method   /ˈmeθ.əd/",
    "ổ cắm": "outlet   /ˈaʊt.let/",
    "nghề nghiệp": "profession   /prəˈfeʃ.ən/ ",
    "chủ đề": "theme   /θiːm/ ",
    "chuỗi": "chain   /tʃeɪn/ ",
    "đăng ký vào": "check in   /tʃek ɪn/",
    "xác nhận": "confirm   /kənˈfɜːm/",
    "chờ đợi": "expect   /ɪkˈspekt/ ",
    "Người quản gia": "housekeeper   /ˈhaʊsˌkiː.pər/",
    "thông báo": "notify   /ˈnəʊ.tɪ.faɪ/",
    "Trích dẫn": "quote   /kwəʊt/",
    "tỷ lệ": "rate   /reɪt/",
    "Dự phòng": "reservation   /ˌrez.əˈveɪ.ʃən/ ",
    "dịch vụ": "service   /ˈsɜː.vɪs/",
    "có được, thu được": "acquire   /əˈkwaɪər/ ",
    "ngưỡng mộ": "admire   /ədˈmaɪər/",
    "bộ sưu tập": "collection   /kəˈlek.ʃən/ ",
    "sự chỉ trích": "criticism   /ˈkrɪt.ɪ.sɪ.zəm/ ",
    "thời trang": "fashion   /ˈfæʃ.ən/ ",
    "giải trí": "leisure   /ˈleʒ.ər/",
    "trả lời": "respond   /rɪˈspɒnd/ ",
    "lịch trình": "schedule   /ˈʃedʒ.uːl/ ",
    "có ý nghĩa": "significant   /sɪɡˈnɪf.ɪ.kənt/",
    "chuyên": "specialize   /ˈspeʃ.əl.aɪz/",
    "quang phổ": "spectrum   /ˈspek.trəm/",
    "thừa nhận": "admit   /ədˈmɪt/",
    "ủy quyền": "authorize   /ˈɔː.θər.aɪz/ ",
    "hộ tống": "escort   /ɪˈskɔːt/",
    "nhận định": "identify   /aɪˈden.tɪ.faɪ/ ",
    "sứ mệnh": "mission   /ˈmɪʃ.ən/ ",
    "giấy phép": "license   /ˈlaɪ.səns/",
    "thích hợp": "pertinent   /ˈpɜː.tɪ.nənt/ ",
    "thủ tục": "procedure   /prəˈsiː.dʒər/ ",
    "tuyên bố": "statement   /ˈsteɪt.mənt/ ",
    "không bắt buộc": "optional   /ˈɒp.ʃən.əl/ ",
    "cám dỗ": "tempt   /tempt/ ",
    "sợ hãi": "thrill   /θrɪl/",
    "tầng": "tier   /tɪər/",
    "phân công": "assignment   /əˈsaɪn.mənt/ ",
    "chọn": "choose   /tʃuːz/ ",
    "cấu tạo": "constitute   /ˈkɒn.stɪ.tʃuːt/",
    "phán quyết": "decision   /dɪˈsɪʒ.ən/",
    "sự va chạm": "impact   /ˈɪm.pækt/",
    "chuyên sâu": "in-depth   /ˈɪn.depθ/",
    "điều tra": "investigate   /ɪnˈves.tɪ.ɡeɪt/",
    "liên kết": "link   /lɪŋk/",
    "đăng ký": "subscribe   /səbˈskraɪb/",
    "kỹ lưỡng": "thorough   /ˈθʌr.ə/",
    "tham khảo ý kiến": "consult   /kənˈsʌlt/ ",
    "điều khiển": "control   /kənˈtrəʊl/",
    "tiện lợi": "convenient   /kənˈviː.ni.ənt/ ",
    "phát hiện": "detect   /dɪˈtekt/",
    "hệ số": "factor   /ˈfæk.tər/ ",
    "sự tương tác": "interaction   /ˌɪn.təˈræk.ʃən/ ",
    "giới hạn": "limit   /ˈlɪm.ɪt/",
    "màn hình": "monitor   /ˈmɒn.ɪ.tər/",
    "tiềm năng": "potential   /pəˈten.ʃəl/ ",
    "mẫu vật": "sample   /ˈsɑːm.pəl/",
    "giác quan": "sense   /sens/",
    "Tình nguyện viên": "volunteer   /ˌvɒl.ənˈtɪər/"
}

//lấy key ngẫu nhiên
function random_item(items)
{
    return items[Math.floor(Math.random()*items.length)]; 
}


function xuly1(){
    var keys = Object.keys(dict)
    var items = random_item(keys);
    document.querySelector('#tu_vung').innerHTML = items
    document.querySelector('#dap_an').innerHTML = dict[items]
    xuly_kytu();
    hint_disable();
}

//đảo nghịch từ điển
function swap(){
    var ret = {};
    for(var key in dict){
      ret[dict[key]] = key;
    }
    dict = ret;
    return dict
}

// xử lý ký tự quá dài
function xuly_kytu(){
    tu_vung = document.querySelector('#tu_vung');
    if ((tu_vung.innerHTML).length >15){
        tu_vung.style.fontSize = "70px";
    }
    else if ((tu_vung.innerHTML).length >24){
        tu_vung.style.fontSize = "50px";
    }
    else {
        tu_vung.style.fontSize = "100px";
    }
}

//gợi ý
function hint(){
    var da = document.querySelector('#dap_an');
    da.style.display = "";
}

function hint_disable(){
    var da = document.querySelector('#dap_an');
    da.style.display = "none";
}

//swap lần đầu
swap();
